### ISSUE TITLE
Cleanup "old" versions 

### ISSUE THREAD

**Issue by tina-junold** [andrewrothstein/ansible-argocd#1]
Hi,

is it possible to add an task to remove old versions to keep the /usr/local/bin directory clean from multiple versions?

Best regards
Tina

**Comment by andrewrothstein** [comment]
I've chosen to not support that in any of my roles. The act of removing old versions is one to do carefully. If I wanted to do that on hosts in inventory I'd do that surgically and separately. In general I try to use these roles to build immutable VM and container images. Through this lens, "removing an old version" == "build a new image with the new version only". 
I apologize if this makes ur life as a user more difficult. Thank you for using my roles.
